### ISSUE TITLE
Travis error: throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by diegoeis** [thingsinjars/Hardy#30]
I'm trying run hardy in travis, but I'm not passing throw this error, some ideas about that?
https://travis-ci.org/diegoeis/locawebstyle/builds/53061854

```
> LocawebStyle@3.7.0 test /home/travis/build/diegoeis/locawebstyle
> node_modules/hardy/bin/hardy --browser=phantomjs test
Hardy v0.0.10
events.js:72
    throw er; // Unhandled 'error' event
    ^
Error: spawn ENOENT
at errnoException (child_process.js:1011:11)
at Process.ChildProcess._handle.onexit (child_process.js:802:34)
npm ERR! Test failed. See above for more details.
npm ERR! not ok code 0
The command "bundle exec rake jasmine:ci && npm test" exited with 1.
Done. Your build exited with 1.
```

My **.travis.yml**

```
before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - sleep 3
  - npm install
  - node_modules/hardy/bin/hardy selenium start
  - python -m SimpleHTTPServer&

 script:
  - bundle exec rake jasmine:ci && npm test
```

and my package:

```
"scripts": {
   "test": "node_modules/hardy/bin/hardy --browser=phantomjs test"
}
```

**Comment by jhamit** [comment]
I was getting this locally on `hardy selenium start` prior to installing the JDK. Have you done that already?
