### ISSUE TITLE
Windows 7 issues

### ISSUE THREAD

**Issue by ghost** [thingsinjars/Hardy#34]
Error:

```
> hardy --browser=firefox,phantom,chrome ./hardy_tests

Hardy v1.1.0
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178
:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\n
odejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "hardy_test"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! rhythm-testing@1.0.0 hardy_test: `hardy --browser=firefox,phanto
m,chrome ./hardy_tests`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rhythm-testing@1.0.0 hardy_test script 'hardy --br
owser=firefox,phantom,chrome ./hardy_tests'.
npm ERR! This is most likely a problem with the rhythm-testing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     hardy --browser=firefox,phantom,chrome ./hardy_tests
npm ERR! You can get information on how to open an issue for this project
 with:
npm ERR!     npm bugs rhythm-testing
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls rhythm-testing
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Rhythm\rhythm-testing\hardy-tests\npm-debug.log
```

**Comment by ghost** [comment]
npm-debug.log contents:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'hardy_test' ]
2 info using npm@2.14.20
3 info using node@v4.4.0
4 verbose run-script [ 'prehardy_test', 'hardy_test', 'posthardy_test' ]
5 info prehardy_test rhythm-testing@1.0.0
6 info hardy_test rhythm-testing@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info rhythm-testing@1.0.0 Failed to exec hardy_test script
9 verbose stack Error: rhythm-testing@1.0.0 hardy_test: `hardy --browser=firefox,phantom,chrome ./hardy_tests`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid rhythm-testing@1.0.0
11 verbose cwd C:\Rhythm\rhythm-testing\hardy-tests
12 error Windows_NT 6.1.7601
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "hardy_test"
14 error node v4.4.0
15 error npm  v2.14.20
16 error code ELIFECYCLE
17 error rhythm-testing@1.0.0 hardy_test: `hardy --browser=firefox,phantom,chrome ./hardy_tests`
17 error Exit status 1
18 error Failed at the rhythm-testing@1.0.0 hardy_test script 'hardy --browser=firefox,phantom,chrome ./hardy_tests'.
18 error This is most likely a problem with the rhythm-testing package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     hardy --browser=firefox,phantom,chrome ./hardy_tests
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs rhythm-testing
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls rhythm-testing
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```
